trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

defaults:
  workingDirectory: $(System.DefaultWorkingDirectory)/Java_pipeline_with_tests_and_packages

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-11-jdk
    java -version
    pwd
    ls -lah
  displayName: 'Install Java 11'

- task: Maven@4
  displayName: Maven Clean Package
  inputs:
    mavenPomFile: '$(System.DefaultWorkingDirectory/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: 'clean package'

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    failTaskOnFailedTests: true

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target/*.jar'
    ArtifactName: 'java-app-jar'
    publishLocation: 'Container'

- task: UniversalPackages@0
  displayName: Publish Universal Package to Feed
  inputs:
    command: 'publish'
    publishDirectory: '$(System.DefaultWorkingDirectory)/target'
    feedsToUse: 'internal'
    vstsFeedPublish: 'YourFeedName'
    vstsFeedPackagePublish: 'SimpleJavaApp'
    packagePublishDescription: 'SimpleJavaApp package'
