trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-11-jdk
    java -version
  displayName: 'Install Java 11'

- task: Maven@4
  inputs:
    mavenPomFile: '$(System.DefaultWorkingDirectory/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: 'clean package'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    failTaskOnFailedTests: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target/*.jar'
    ArtifactName: 'java-app-jar'
    publishLocation: 'Container'

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(System.DefaultWorkingDirectory)/target'
    feedsToUse: 'internal'
    vstsFeedPublish: 'YourFeedName'
    vstsFeedPackagePublish: 'SimpleJavaApp'
    packagePublishDescription: 'SimpleJavaApp package'
