trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-11-jdk
    java -version
  displayName: 'Install Java 11'

- task: Maven@4
  displayName: Maven Clean Package
  inputs:
    mavenPomFile: '$(system.defaultWorkingDirectory)/Java_pipeline_with_tests_and_packages/SimpleJavaApp/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: 'clean package'

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    failTaskOnFailedTests: true

# - task: PublishBuildArtifacts@1
#   displayName: Publish Build Artifacts
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)/target/*.jar'
#     ArtifactName: 'java-app-jar'
#     publishLocation: 'Container'

# - task: UniversalPackages@0
#   displayName: Publish Universal Package to Feed
#   inputs:
#     command: 'publish'
#     publishDirectory: '$(System.DefaultWorkingDirectory)/target'
#     feedsToUse: 'internal'
#     vstsFeedPublish: 'YourFeedName'
#     vstsFeedPackagePublish: 'SimpleJavaApp'
#     packagePublishDescription: 'SimpleJavaApp package'

- task: Maven@4
  displayName: 'Publish to ADO techbrain-feed'
  inputs:
    mavenPomFile: '$(system.defaultWorkingDirectory)/Java_pipeline_with_tests_and_packages/SimpleJavaApp/pom.xml'
    goals: 'deploy'
    options: '-DskipTests'
    publishJUnitResults: false
    mavenOptions: '-Xmx1024m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
